* OrgHexagon

#+begin_quote
The universe (which others call the Library) is composed of an
indefinite and perhaps infinite number of hexagonal galleries, with
vast air shafts between, surrounded by very low railings. (...)
The idealists argue that the hexagonal rooms are a necessary form of
absolute space or, at least, of our intuition of space.

                    - Jorge Luis Borges, The Library of Babel
#+end_quote

** TODO Introduction

OrgHexagon is a simple Sinatra application that features an API
which can be called through Emacs to publish texts written in org-mode.

*** Objectives

- [ ] Have an API to publish texts written in org-mode from Emacs through HTTP
- [ ] Relatively simple to deploy (e.g. not having to setup Emacs on the server)
- [ ] Minimal layout design

** TODO How to setup

Clone this repository:

#+begin_src sh
git clone git://github.com/wallyqs/org-hexagon
bundle install
bundle package
#+end_src

You need to have a MongoDB data store available so that the texts can be saved,
so you also need to modify the =config/mongo.yml= to point it your MongoDB.

Some notes about the setup:

- It uses the =org-ruby= gem to render the org-mode texts to HTML. This saves
  having to install a full Emacs instance on your server.

- By default it is going to use =Coderay= to highlight the source blocks.
  In case you want to use =pygments.rb= you need to include this gem
  in the Gemfile.

- It includes some built-in support to run it on Cloudfoundry.
  Just =create-service mongodb= and =bind-service= your MongoDB to save the texts.

** TODO Setting up the client

- Load the =org-hexagon.el= client included in this repo.

- Set the following in your =.emacs=:
  #+begin_src emacs-lisp
    (setq org-hexagon-auth '("librarian" . "secret"))
  #+end_src

** TODO How to use

Open a buffer with some org-mode text:

#+begin_src org
  * Hello world

  Writing using =org-mode= markup to be published.

#+end_src

Then use =M-x org-hexagon-sync-text= in the buffer to publish org-mode text.

You will be able to view your post online at =http://your-url.com/texts=.

** TODO Using PROPERTIES to modify publishing settings of your text

You can use the =PROPERTIES= drawer from org-mode to configure
the way you want to publish the text.

For example, if you post a the text with the following properties:

#+begin_src org
  * Hello world
    :PROPERTIES:
    :id:       1
    :slug:     hello-world
    :shelf:    blog
    :public:   yes
    :END:
#+end_src

A publicly accessible url =http://your-url.com/blog/hello-world= will be available,
as well as a url like =http://your-url.com/texts/1= which only you will be able to browse.

* LICENSE

#+begin_quote
Copyright (C) 2012 Quevedo, Waldemar

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
#+end_quote
